// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"io"
)

// Injectors from wire.go:

func InitializeMyStruct(ctx *context.Context, msgs []Message, reader io.Reader, writer io.Writer) (MyStruct, error) {
	option := Option{
		Messages: msgs,
		Writer:   writer,
		Reader:   reader,
	}
	myStruct, err := NewMyStruct(ctx, option)
	if err != nil {
		return MyStruct{}, err
	}
	return myStruct, nil
}
