// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeFooBar() FooBar {
	foo := NewFoo()
	fooBar := FooBar{
		MyFoo: foo,
	}
	return fooBar
}
