// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(message string) Event {
	mainMessage := NewMessage(message)
	greeter := NewGreeter(mainMessage)
	event := NewEvent(greeter)
	return event
}
